apiVersion: batch/v1
kind: CronJob
metadata:
  name: python-job
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: python-service-account
          containers:
            - name: my-python
              image: pasiechnyk/my-python:1.3
              command: [ "python", "/app/main.py" ]
          restartPolicy: OnFailure
          imagePullSecrets:
            - name: python-secret